### ISSUE TITLE
Type error on Prioritized DQN ( unpacking list with star operation)

### ISSUE THREAD

**Issue by ugurkanates** [Curt-Park/rainbow-is-all-you-need#21]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-46-4326fee8443c> in <module>()
----> 1 agent.train(num_frames)

1 frames
<ipython-input-44-3565ceee028a> in step(self, action)
    134         if not self.is_test:
    135             self.transition += [reward, next_state, done]
--> 136             self.memory.store(self.transition)
    137 
    138         return next_state, reward, done

TypeError: store() missing 4 required positional arguments: 'act', 'rew', 'next_obs', and 'done'

Platform is google collab by the way

**Comment by Curt-Park** [comment]
I will check it.

**Comment by Curt-Park** [comment]
I think you missed a star (*) in front of self.transition in the line of 136 as follows.
`self.memory.store(*self.transition)`
I've checked it runs well on Colab execution.
