### ISSUE TITLE
redundant max in double dqn

### ISSUE THREAD

**Issue by DongukJu** [Curt-Park/rainbow-is-all-you-need#25]
In double dqn, I found that there is max Q(~~~, argmaxQ(~~~)).

Do we need max even though we have argmax in Q?

I think the max is redundant.

Would you kindly check this for reducing confusion?

**Comment by MrSyee** [comment]
Hi. @DongukJu 

As you said, equation 1 and 2 mean same thing. But equation 2 is a variation of the expression to transform it into double Q-learning. As you look at equation 3 closely, the two Q values are different two thetas (theta, theta '). Double Q-learning is a way **to reduce over-estimation** by updating each other using two Q-values. To explain the process of change, therefore, it would be better to use the expression as it is.

equation 1. 
![image](https://user-images.githubusercontent.com/17582508/70894997-73697980-2031-11ea-8026-d720598955da.png)

equation 2. 
![image](https://user-images.githubusercontent.com/17582508/70895034-85e3b300-2031-11ea-9114-3399eeb50b80.png)

equation 3. ![image](https://user-images.githubusercontent.com/17582508/70895051-8bd99400-2031-11ea-8b70-7b0ef3d185dc.png)


Thank you!

**Comment by DongukJu** [comment]
Dear @MrSyee,

Thanks for your reply.

As you mentioned, I agree with the importance of the variation.

What I meant was that, 
![image](https://user-images.githubusercontent.com/22473161/70903623-9a7c7700-2042-11ea-8442-d25ba6cc4cf8.png)

max_a in eq 2 and eq 3 is redundant.

As far as I understand correctly, the max is doing nothing there.

If you want to convey the same intuition to the readers, we might allow this redundancy, but it may still cause confusion.

The max is supposed to do something, but nothing.

Would you kindly clarify this?

**Comment by MrSyee** [comment]
Dear @DongukJu

Oh. You're right. I'm sorry that I couldn't figure out the typo even after reading your comment.
I'll modify this problem.

Thanks for your insight.

**Comment by Curt-Park** [comment]
The typo is fixed. Thanks.
