### ISSUE TITLE
Google Drive ,Saving,Loading,Resuming Features.

### ISSUE THREAD

**Issue by kiranmaya** [Curt-Park/rainbow-is-all-you-need#34]
Need ,these saving and loading ,resuming models states   , i tried to write that , but i am confused  somewhere between gpu weights ,cpu weights . or we need to create network class before loading ,or loading contains network definitions etc .

**Comment by Curt-Park** [comment]
I will give you an example of [DQN](https://nbviewer.jupyter.org/github/Curt-Park/rainbow-is-all-you-need/blob/master/01.dqn.ipynb)'s things to be considered...

**1. for resuming training:**
- Replay memory: self.memory
- Hyperparameters: self.batch_size, self.epsilon, self.epsilon_decay, self.max_epsilon, self.min_epsilon, self.target_update, self.gamma
- Networks: self.dqn, self.dqn_target
- Optimizer: self.optimizer

**2. for saving and loading a trained model (used in test mode only):**
- Hyperparameters: self.epsilon
- Networks: self.dqn

**Comment by Curt-Park** [comment]
Please let me know here or through another issue if you meet any other obstacles.
