### ISSUE TITLE
Running on Atari Games

### ISSUE THREAD

**Issue by FarhaParveen919** [Curt-Park/rainbow-is-all-you-need#36]

**Comment by FarhaParveen919** [comment]
Dear Jinwoo,

Thank you very much for putting up this code. Running it on Jupyter notebook has been very useful and informative.

I am trying to run the code (rainbow.ipynb) now on Atari games such as SpaceInvaders-v0.  

I tried the following :

num_frames = 10000
memory_size = 1000000
batch_size = 32
target_update = 8000
# train
agent = DQNAgent(env, memory_size, batch_size, target_update)
agent.train(num_frames)

However, I am receiving a matrix mismatch error (attached). I realize that porting the code to Atari is not straight forward, and might need the techniques used in https://github.com/medipixel/rl_algorithms. 

Before going through the above github in more detail, I was wondering whether you had an example of running any Atari game with the existing .ipynb notebook.  

![atarierror](https://user-images.githubusercontent.com/56920928/81607422-f4585180-93d4-11ea-8515-bccbd56199a0.png)


Regards,
Farha

**Comment by Curt-Park** [comment]
This repository doesn't consider to cover wide range of RL environments so as to focus on delivering the basics of RL techniques as a tutorial. Unfortunately, I don't have any ipynb example for it, so you may need to employ things not introduced in this repository to run Atari environments. I feel sorry to say that.
