### ISSUE TITLE
"indices" in the N-step ReplayBuffer undefined

### ISSUE THREAD

**Issue by yellowpuppy** [Curt-Park/rainbow-is-all-you-need#37]
In the sameple_batch function in "08.rainbow.ipynb", the returned variable “indices” was not defined
`
def sample_batch(self) -> Dict[str, np.ndarray]:
    idxs = np.random.choice(self.size, size=self.batch_size, replace=False)

    return dict(
        obs=self.obs_buf[idxs],
        next_obs=self.next_obs_buf[idxs],
        acts=self.acts_buf[idxs],
        rews=self.rews_buf[idxs],
        done=self.done_buf[idxs],
        # for N-step Learning
        indices=indices,
    )
`
It should be "indices=idxs" instead? Did I miss some thing?

**Comment by Curt-Park** [comment]
Thanks for pointing it out. I will push a PR to fix it.

**Comment by Curt-Park** [comment]
It is fixed. Thanks again.
