### ISSUE TITLE
Categorical DQN parameters for Acrobot

### ISSUE THREAD

**Issue by kka0009** [Curt-Park/rainbow-is-all-you-need#39]
Do you have any suggestions on what values should be used for the Categorical DQN parameters: v_min, v_max, atom_size if evaluating on Acrobot-v1 instead of CartPole-v0?

**Comment by MrSyee** [comment]
Hi @kka0009 !
In general, `v_min`, `v_max` for Categorical DQN is set depends on reward range of environment.
The reward of Acrobot-v1 is -1 or 0 according to [gym code](https://github.com/openai/gym/blob/bf7e44f680fa237a3c3ae127eb096f0a9daa62a9/gym/envs/classic_control/acrobot.py#L130), so it would be better to set `v_min`, `v_max` as -1, 0. For `atom_size`, `51` is usually the best suggested in the paper, but if reward range is too big, you should set it bigger.

However this is just a guideline, and you should choose them through many experiments to make the best agent.

**Comment by kka0009** [comment]
Hi, thank you for taking the time to reply. I checked the [cartpole code](https://github.com/openai/gym/blob/bf7e44f680fa237a3c3ae127eb096f0a9daa62a9/gym/envs/classic_control/cartpole.py#L138) and there the reward is also 1. However in the config for your implementation, you've set the V_max to 200 and the V_min to 0. Sorry, I still didn't understand why that's the case then. 

I had a look at the [Google Brain Dopamine implementation](https://github.com/google/dopamine/blob/master/dopamine/agents/rainbow/configs/c51_cartpole.gin) and it seems they chose -10,10 however those values don't seem to work with your C51 implementation. 

Thanks again for taking the time to review this query.

**Comment by kka0009** [comment]
Hi, thank you for taking the time to reply. I found suitable values for V_min and V_max through further experimentation as you had suggested after fixing the number of atoms. 

A final question I had was if there was any bibtex that could be used to cite both you and Kyunghwan Kim for this repository.

**Comment by kka0009** [comment]
Thank you. I found suitable values for V_min and V_max after fixing the number of atoms.
