### ISSUE TITLE
奇怪的是，rainbow的代码容易出现内存不足的问题 interrupted by signal 9: SIGKILL

### ISSUE THREAD

**Issue by luo-li-ba-suo** [Curt-Park/rainbow-is-all-you-need#43]
是缓存器的问题吗

**Comment by Curt-Park** [comment]
Sorry, I don't speak Chinese.

**Comment by luo-li-ba-suo** [comment]
I have found the reason why it comes to not enough memory: the scores and the losses in DQNAgent should be manually constrainted to a capicity that is not too large.

**Comment by Curt-Park** [comment]
Also you can reduce the mini batch size or try it on Colab.
Thanks for sharing the reason of the issue.
I will close this issue.
