### ISSUE TITLE
Atari

### ISSUE THREAD

**Issue by abbas-tari** [Curt-Park/rainbow-is-all-you-need#45]
Your rainbow implementation here is awesome!! So goood
please consider adapting it for Atari games for beginners

**Comment by Curt-Park** [comment]
It would be great if you can share your idea with simple implementation.
This project is opened to everyone, and you can join anytime. :)

**Comment by Yuanzhuo-Liu** [comment]
File "D:\Paper\double_tf\segment_tree.py", line 65, in __setitem__
    self.tree[idx] = self.operation(self.tree[2 * idx], self.tree[2 * idx + 1])
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown
Quitting (on error).
Hi! That's a problem. Do you have any good suggestions?

**Comment by Curt-Park** [comment]
@Yuanzhuo-Liu 
I think you imported a wrong module that has the same name as the intended one.
You can see `segment_tree` actually used on this repo has a different logic in line 65.
https://github.com/Curt-Park/rainbow-is-all-you-need/blob/master/segment_tree.py#L65

<img width="707" alt="스크린샷 2021-04-03 오후 7 33 40" src="https://user-images.githubusercontent.com/14961526/113476003-7fda4580-94b3-11eb-9875-f953a2aa79f1.png">

**Comment by Curt-Park** [comment]
Please reopen the issue if you want to discuss more.
