### ISSUE TITLE
V_min and V_max - Rainbow DQN

### ISSUE THREAD

**Issue by andreasceid** [Curt-Park/rainbow-is-all-you-need#50]
Hello,

I'm studying your [Rainbow DQN](https://github.com/Curt-Park/rainbow-is-all-you-need/blob/master/08.rainbow.ipynb) tutorial. I'm trying to understand why is `V_min` set to 0 and `V_max` to  200. Most of Rainbow DQN implementations have those variables set to -10 and 10 respectively.

**Comment by Curt-Park** [comment]
v_min and v_max can be tuned according to the return value scale of the environment you use.

I assumed that the state value of Cartpole in a range from 0 to 200.

**Comment by andreasceid** [comment]
Do you mean the reward value scale? I don't know what the return value scale of an environment is. I'm a beginner in RL so this might not be the greatest of questions.

**Comment by Curt-Park** [comment]
OpenAI spinning-up will give you the basic idea and mathematical definition of Return.

https://spinningup.openai.com/en/latest/spinningup/rl_intro.html#reward-and-return

**Comment by andreasceid** [comment]
I take that since we use `gamma` in case of Rainbow DQN, the return is type of infinite-horizon discounted return, right?
