### ISSUE TITLE
does this work with mountaincar and other gym environments

### ISSUE THREAD

**Issue by simin75simin** [Curt-Park/rainbow-is-all-you-need#51]
if i just chagne cartpole to mountaincar in chapter 8, it pretty much does not work. is there a way to make it work though? do you consider making it like stable baselines, running on all sorts of environments?

thanks.

**Comment by Curt-Park** [comment]
1. You should set the parameters so that it aligns well with another environment, especially in terms of C51.
2. Most of implementations here are originated from [RL Algorithm Repo](https://github.com/medipixel/rl_algorithms), which is designed as a general RL framework.

**Comment by simin75simin** [comment]
thanks
