### ISSUE TITLE
clear momory during n_step_learning

### ISSUE THREAD

**Issue by PigUnderRoof** [Curt-Park/rainbow-is-all-you-need#54]
In the training loop, it might make sense to call self.memory_n_step.n_step_buffer.clear() when an episode is done to avoid (final->initial) transitions.

**Comment by Curt-Park** [comment]
It doesn't matter.
The logic considers the case that `n_step_buffer` has two episodes' transitions.
In that case, it ignores the previous episode's transitions.

**Comment by Curt-Park** [comment]
I will close this issue. If you have more things to discuss, please reopen.
