### ISSUE TITLE
N-step ReplayBuffer's store use the wrong act?

### ISSUE THREAD

**Issue by ty2000** [Curt-Park/rainbow-is-all-you-need#8]
In the N-step ReplayBuffer, the store() method stores act into the memory

self.acts_buf[self.ptr] = act

should't this be action instead? i.e.

self.acts_buf[self.ptr] = action

**Comment by Curt-Park** [comment]
Thanks for pointing it out. I will fix it asap.

**Comment by Curt-Park** [comment]
Fixed. Thanks for your opinion :)
